name: Deploy on PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    permissions:
      id-token: write
    uses: greenbone/workflows/.github/workflows/deploy-pypi.yml@main
    with:
      pypi-url: https://pypi.org/project/autohooks-plugin-ruff/
